# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

#before_install:
#  - sudo apt-get update && sudo apt-get install libgdal1h libproj-dev
#  - sudo apt-get update && sudo apt-get install libgdal1h libgdal-dev libgdal1-dev libproj-dev
#  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
#  - chmod 755 ./travis-tool.sh
#  - apt-cache search gdal
#  - apt-cache showpkg libgdal1
#  - apt-cache showpkg libgdal-dev
#  - apt-cache showpkg libgdal1-dev
#  - sudo apt-get update
#  - ./travis-tool.sh install_aptget gdal-bin libgdal1 libgdal1-dev netcdf-bin libproj-dev
#  - ./travis-tool.sh bootstrap
#  - ./travis-tool.sh install_r_binary rjava
#  - apt-cache search gdal
#  - apt-cache showpkg libgdal1
#  - apt-cache showpkg libgdal-dev
#  - apt-cache showpkg libgdal1-dev
#  - ./travis-tool.sh install_deps
#  - ./travis-tool.sh github_package assertthat
#  - ./travis-tool.sh run_tests

#  - sudo apt-get update
#  - sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev netcdf-bin libproj-dev
#  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
#  - chmod 755 ./travis-tool.sh
#  - ./travis-tool.sh bootstrap
#  - ./travis-tool.sh install_deps
#  - ./travis-tool.sh install_r rgdal
#  - ./travis-tool.sh github_package hadley/testthat

#   - ./travis-tool.sh aptget_install gdal-bin libgdal1-dev
#   - sudo apt-get update && sudo apt-get install libgdal-dev libgdal1-dev libproj-dev
#   - sudo apt-get install aptitude # install aptitude as an alternative to apt-get
#   - sudo aptitude install libgdal-dev # install the package (you may have to respond to queries here)
#   - sudo aptitude install libproj-dev # install the proj.4 projection library
#   - sudo aptitude install gdal-config


env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
